name: Release

on:
  workflow_run:
    workflows: ["Crawl"]
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'schedule'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure diff.sh is executable
        run: chmod +x ./diff.sh

      - name: Run diff.sh
        run: ./diff.sh
