name: Release

on:
  workflow_run:
    workflows: ["Crawl"]
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'schedule'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set Git Config
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config core.filemode false

      - name: Ensure diff.sh is executable
        run: chmod +x ./diff.sh

      - name: Run diff.sh
        run: ./diff.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
